apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-observer
  namespace: monitoring
  labels:
    app: link-observer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: link-observer
  template:
    metadata:
      labels:
        app: link-observer
    spec:
      containers:
        - name: link-observer
          image: gcr.io/eecom-1138/l0r3zz/link-observer:v1
          ports:
            - containerPort: 8001
#          volumeMounts:
#            - name: prometheus-config-volume
#              mountPath: /etc/prometheus/
#            - name: prometheus-storage-volume
#              mountPath: /prometheus/
#      volumes:
#        - name: prometheus-config-volume
#          configMap:
#            defaultMode: 420
#            name: prometheus-server-conf
#        - name: prometheus-storage-volume
#          emptyDir: {}
